### ISSUE TITLE
"this.state.foo is undefined" 

### ISSUE THREAD

**Issue by HE-is** [jedireza/aqua#230] opened 2017-08-07 15:24 UTC
Sorry to bother again; I can't figure this out. I've been trying to find where I'm going wrong but haven't been able to despite working on this all weekend. 
I'm just trying to add another set of user info fields. It's initially setting them in the mongodb fine, it's just that the store isn't holding it or something. Maybe something to do with reducers like you mentioned last week. Sorry again for my noobiness; this is a learning experience for me. I attached the client files... 
~~client.tar.gz~~

Thanks heaps!

**Comment by HE-is** [comment] 2017-08-07 15:34
[server.tar.gz](https://github.com/jedireza/aqua/files/1205315/server.tar.gz)
Here's the server code aswell if there's problems in there too...

**Comment by jedireza** [comment] 2017-08-07 15:46
You're not supplying enough information for anyone to help. You should provide the stack trace for the error.

And instead of adding sharing code via files we have to download (which I've removed), you should create a reproducible example and host it on a GitHub.

This is likely to be caused by not providing default values in your redux stores.

**Comment by HE-is** [comment] 2017-08-07 21:44
Okay I've been working on this constantly, skipping lunch, to try and figure this out.
What should I do? Should I put the whole project on github to be used as a reproducible example?
Sorry to bother; I hope after I learn that I will be able to help and contribute in some way.

**Comment by jedireza** [comment] 2017-08-07 23:56
> How do I provide a stack trace?

I'm glad you asked. 😄 `this.state.foo is undefined` is the error message, but usually when you see that you see a list of function calls and line numbers, that's the stack trace. That helps debug what could've caused the issue. You can either find this on the command line for server-side code and in the browser console for client-side code.

https://www.quora.com/Whats-different-between-a-stack-trace-and-an-error-message

**Comment by jedireza** [comment] 2017-08-12 03:28
Closing for now. Open a new issue when you have more information.

Thanks for being active with the project. 🙏

**Closed by jedireza** 2017-08-12 03:28 UTC
Labels: question

**Comment by HE-is** [comment] 2017-08-15 05:51
Thanks for giving guidance! I've been learning a ton!
I figured it out; I plan to write an overview of my Aqua endeavours and
make it into some sort of quickstart guide for noobs like me. Haha.
