### ISSUE TITLE
Can't create new users

### ISSUE THREAD

**Issue by alex-dixon** [jedireza/aqua#18] opened 2015-04-04 07:07 UTC
Hello. I'm getting the following error when I run npm start and haven't been able to figure out why:

```
Debug: auth, unauthenticated, error, session
    Error: Unauthorized
    at Object.exports.create (/Users/alexdixon/aqua-template/node_modules/boom/lib/index.js:21:17)
    at Object.exports.unauthorized (/Users/alexdixon/aqua-template/node_modules/boom/lib/index.js:86:23)
    at validate (/Users/alexdixon/aqua-template/node_modules/hapi-auth-cookie/lib/index.js:114:49)
    at Object.scheme.authenticate (/Users/alexdixon/aqua-template/node_modules/hapi-auth-cookie/lib/index.js:179:13)
    at /Users/alexdixon/aqua-template/node_modules/hapi/lib/auth.js:214:30
    at internals.Protect.run (/Users/alexdixon/aqua-template/node_modules/hapi/lib/protect.js:56:5)
    at authenticate (/Users/alexdixon/aqua-template/node_modules/hapi/lib/auth.js:205:26)
    at internals.Auth._authenticate (/Users/alexdixon/aqua-template/node_modules/hapi/lib/auth.js:328:5)
    at internals.Auth.authenticate (/Users/alexdixon/aqua-template/node_modules/hapi/lib/auth.js:164:17)
    at /Users/alexdixon/aqua-template/node_modules/hapi/lib/request.js:331:13
```

When trying to create a new user account I get this error:

```
/Users/alexdixon/aqua-template/server/api/signup.js:170
                var credentials = user.username + ':' + results.session.key;
                                      ^
TypeError: Cannot read property 'username' of undefined
    at /Users/alexdixon/aqua-template/server/api/signup.js:170:39
    at /Users/alexdixon/aqua-template/node_modules/async/lib/async.js:454:17
    at /Users/alexdixon/aqua-template/node_modules/async/lib/async.js:444:17
    at Array.forEach (native)
    at _each (/Users/alexdixon/aqua-template/node_modules/async/lib/async.js:46:24)
    at Object.taskComplete (/Users/alexdixon/aqua-template/node_modules/async/lib/async.js:443:13)
    at processImmediate [as _immediateCallback] (timers.js:345:15)
```

Both occur just after cloning the repo and following the instructions. I even used a gmail address when running npm run setup. :D

**Comment by jedireza** [comment] 2015-04-05 01:19
Thanks for creating an issue and reporting the bug. :cake:

I have confirmed the bug with the sign up which is fixed with #19. The first snippet you showed doesn't actually happen on server start, but when you `POST` to `/signup` since that route is configured to `try` session authentication (so we can set the session). I don't think it's cause for worry.

**Closed** 2015-04-05 01:19 UTC
Labels: bug
