### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by arb** [jedireza/aqua#2] opened 2015-02-18 18:12 UTC
Is there a place where how things fit together is discussed? There are a lot of files here and it's not clear to me what does what.

For example, is this a SPA? If so, why are there different routes on the server for the views? 
Where is the client side router set up? 
I see each page exports it's own routes for the client side router, but there are they bundled up?

**Comment by jedireza** [comment] 2015-02-19 02:06
Thanks for opening an issue.

 > Is there a place where how things fit together is discussed?

Not yet. I'll use this conversation to begin a technical walk through and add it to the wiki.

 > Is this a SPA? If so, why are there different routes on the server for the views? 

It's more like a few single page apps. The home and about pages just demonstrate simple server side rendering. The signup and contact pages are each a mini app. They help demonstrate flux in a super simple use case (one form). The login page does have a few pages it manages though. You'll notice if you click on the forgot password link from the login page, it'll load instantly. Then the account and admin areas are each larger one page apps.

 > Where is the client side router set up?

You'll find a `Routes.jsx` file inside of each page that manages routes. For example:

 - https://github.com/jedireza/aqua/blob/master/client/pages/account/Routes.jsx
 - https://github.com/jedireza/aqua/blob/master/client/pages/admin/Routes.jsx
 - https://github.com/jedireza/aqua/blob/master/client/pages/login/Routes.jsx

Are the three pages that manage their own routes.

 > I see each page exports it's own routes for the client side router, but there are they bundled up?

We've configured webpack to bundle each page into it's own file along with a core file that contains code shared across pages.

- - - - -

I'm happy to answer questions so let's keep this thread open while we find the most common ones.

**Comment by arb** [comment] 2015-02-19 14:25
I see those routes, but they are being exported... where is the React router object that uses them?
Why did you choose to mix gulp and webpack when webpack can do everything gulp can do and then some?

**Comment by jedireza** [comment] 2015-02-19 16:06
> I see those routes, but they are being exported... where is the React router object that uses them?

Each page has an entry point, the convention has been to name it `index.jsx` in the root of that page's directory, for example:

 - https://github.com/jedireza/aqua/blob/master/client/pages/login/index.jsx
 - https://github.com/jedireza/aqua/blob/master/client/pages/admin/index.jsx
 - https://github.com/jedireza/aqua/blob/master/client/pages/login/index.jsx

> Why did you choose to mix gulp and webpack when webpack can do everything gulp can do and then some?

I was originally using browserify and gulp. At one point I had some trouble getting the bundle file sizes to be reasonable. I came across the webpack article ["usage with gulp"](http://webpack.github.io/docs/usage-with-gulp.html), swapped out browserify and was pretty satisfied with the file sizes. Also, there are some tasks like `$ gulp clean` that I didn't see alternatives for.

I'm a fan of simplifying stuff. I'm not married to webpack or gulp. This was my least favorite part of building the app so far :wink:.

- - - - -

Great questions. Keep them coming.

**Comment by ldesplat** [comment] 2015-02-21 00:52
Hopefully, I am allowed to hijack this a bit :)
1) You have given me lots of ideas with this project, so thank you.
  - Love the test coverage. I attempted to use jsdom in another project with lab and that messed with my test coverage reporting. So this is very interesting the way you have done it here.
  - I agree with you, setting up the mess of webpack, gulp, browserify, ... is very uninspiring
  - Thanks for showing an example of confidence. I've always had a hard time understanding how to use it.

2) It is a bummer, we have to compile the .jsx files in the client directory to .react.js for code coverage. I am guessing there is no other reason? I will attempt to look at the lab side of it again since I have similar troubles :(

3) It would be great to see an actual isomorphic example of the same react code being server side and client side rendered. I know it forces a lot of questions though. Right now, if you go to the contact page for example with javascript disabled, you do not see the form.

**Comment by jedireza** [comment] 2015-02-21 02:02
> 1) You have given me lots of ideas with this project, so thank you.

:pray: no, thank you.

> Thanks for showing an example of confidence. I've always had a hard time understanding how to use it.

Confidence is really great. I hope we're using it they way it was intended.

> 2) It is a bummer, we have to compile the .jsx files in the client directory to .react.js for code coverage. I am guessing there is no other reason? I will attempt to look at the lab side of it again since I have similar troubles :(

Yes that's the only reason we're creating `*.react.js` files. I'm not too thrilled about it but, I like `lab` way too much :grin:. I thought we were getting close with https://github.com/hapijs/lab/issues/306. You might have closed that issue a little soon. I don't know much about sourcemaps, but there is a flag in `lab` to use them. I'm confident we'll figure it out soon enough.

> 3) It would be great to see an actual isomorphic example of the same react code being server side and client side rendered. I know it forces a lot of questions though.

So far, I've purposefully stayed away from isomorphic design patterns. Isomorphic apps require a level of assumptions/opinions I didn't want to introduce or commit to. I've used Aqua as a learning experiment, to build a larger-sized app with a vanilla Flux implementation.

We're doing a bunch of great stuff with isomorphic JavaScript at Yahoo with [Fluxible](http://fluxible.io/) though, if you haven't, please check it out. Disclaimer: I joined the Fluxible team last November.

> Right now, if you go to the contact page for example with javascript disabled, you do not see the form.

I'm not sure if that's a problem Aqua should try to solve. Or do you mean just adding `<noscript>Your experience is lacking.</noscript>` as a basic warning to the user?

I'd like Aqua to stay light, modern and forward thinking. But we should define what browsers/experiences we expect support for and mention it in the README.

**Comment by ldesplat** [comment] 2015-02-21 09:46
> Yes that's the only reason we're creating *.react.js files. I'm not too thrilled about it but, I like lab way too  much :grin:. I thought we were getting close with hapijs/lab#306. You might have closed that issue a little soon. I don't know much about sourcemaps, but there is a flag in lab to use them. I'm confident we'll  figure it out soon enough.

I have submitted a start of a [PR#311](https://github.com/hapijs/lab/pull/311) to lab, so we'll see. I actually have it working with aqua.

> We are doing a bunch of great stuff with isomorphic JavaScript at Yahoo with Fluxible though, if you haven't, please check it out.

Will definitely check it out!

> I'm not sure if that's a problem Aqua should try to solve. Or do you mean just adding <noscript>Your experience is lacking.</noscript> as a basic warning to the user?

I think, keeping focus on what Aqua is supposed to be is great. I was just making the point that potentially search engines and obviously those without javascript will not be able to see the form and that's fine. I think defining that javascript must be enabled for some parts of the website to be very reasonable :)

**Comment by sthagman** [comment] 2015-02-21 19:42
This is a great project to find for someone like me who just got interested in trying to use React, Flux, and Hapi.  Also Fluxible looks really cool and I will definitely be checking it out as well.

Onto my question:
I understand a lot of what is going on but the overall flow of the application seems lost on me.  I wonder if you could do quick step-by-step of how the application initializes itself.

For example:
1. Hapi receives HTTP Request for '/index'
2. ....
3. React and Flux are fully initialized on the client.

If you could touch on these topics that would be great as well:
- What is sent down in the initial request?
- What if anything is rendered on the server?
- When does react-router take over and when does the view just get rendered on the server if at all?

I think that this would not only be helpful to me, but would be a great quick addition to the README while you work on a more substantial documentation of the code.

**Comment by bewest** [comment] 2015-02-21 21:19
Is this intended to be a next-gen drywall?

It looks like dealing with groups is a bit easier?
There's a new REST api?

I changed my mind on earlier integration as a module, and am now looking at dropping in `http-proxy`: when user is logged into drywall/aqua process, proxy to backend target, otherwise use the local app logic/views etc for auth management.  Works fairly well as quick prototype, but now looking at using `express.Router( )` to keep drywall's middleware such as body parsing separate from the proxy logic.

**Comment by jedireza** [comment] 2015-02-22 01:45
@sthagman 

> This is a great project to find for someone like me who just got interested in trying to use React, Flux, and Hapi. Also Fluxible looks really cool and I will definitely be checking it out as well.

Great to hear it.

> What is sent down in the initial request? What if anything is rendered on the server? When does react-router take over and when does the view just get rendered on the server if at all?

These routes are handled by the web server. They are responsible for rending the initial page. (I've linked them to their handlers)

 - [`/`](https://github.com/jedireza/aqua/blob/master/server/web/home/index.js)
 - [`/about`](https://github.com/jedireza/aqua/blob/master/server/web/about/index.js)
 - [`/account/{glob*}`](https://github.com/jedireza/aqua/blob/master/server/web/account/index.js)
 - [`/admin/{glob*}`](https://github.com/jedireza/aqua/blob/master/server/web/admin/index.js)
 - [`/contact`](https://github.com/jedireza/aqua/blob/master/server/web/contact/index.js)
 - [`/login/{glob*}`](https://github.com/jedireza/aqua/blob/master/server/web/login/index.js)
 - [`/signup`](https://github.com/jedireza/aqua/blob/master/server/web/signup/index.js)

You'll notice that `/account`, `/admin` and `/login` have that `{glob*}` definition in their path. This is a wildcard param ([see the hapi routing tutorial](http://hapijs.com/tutorials/routing)). So for example, our login handler will handle requests for `/login`, `/login/forgot` and also `/login/nothing`. Yes, we send the exact same response to each of those requests.

Client-side each page has an entry point. Let's focus on the ones with routing.

 - https://github.com/jedireza/aqua/blob/master/client/pages/login/index.jsx ([routes](https://github.com/jedireza/aqua/blob/master/client/pages/login/Routes.jsx))
 - https://github.com/jedireza/aqua/blob/master/client/pages/account/index.jsx ([routes](https://github.com/jedireza/aqua/blob/master/client/pages/account/Routes.jsx))
 - https://github.com/jedireza/aqua/blob/master/client/pages/admin/index.jsx ([routes](https://github.com/jedireza/aqua/blob/master/client/pages/admin/Routes.jsx))

This is where things get started on the client. You'll notice this at the bottom of entry point file:

```js
if (!module.parent) {
    window.app = App;
    App.blastoff();
}
```

This is just saying, if we're not being `require`d, assign a reference to the `App` on the window object and execute `App.blastoff()`. _This pattern allows us to more cleanly test the entry point._

After that it's just react router doing it's magic.

> I think that this would not only be helpful to me, but would be a great quick addition to the README while you work on a more substantial documentation of the code.

Agreed.

- - - - - -

Great questions. I hope I addressed everything well enough.

**Comment by jedireza** [comment] 2015-02-22 02:05
@bewest 

> Is this intended to be a next-gen drywall?

Yes and no. I'd like to see [Drywall](https://github.com/jedireza/drywall) remain as the Express/MVC version. I talk more about this here: https://github.com/jedireza/drywall/issues/268.

> It looks like dealing with groups is a bit easier?

Yeah instead of having an array of groups, we're just using [an object where the keys are the group id and the value is the name](https://github.com/jedireza/aqua/blob/ba0319272fe6510fd55744526e95a542d4ddbb1b/server/models/admin.js#L97).

> There's a new REST api?

Yeah. Before Aqua I released [Frame](https://github.com/jedireza/frame), which is just a user system API, no front-end implementation.

- - - - -

:+1: Thanks for bringing these things up.

**Comment by jedireza** [comment] 2015-02-22 07:22
@ldesplat I'm really glad to see that PR for `lab`. :cake:

**Comment by bewest** [comment] 2015-02-22 19:18
Adding a prefix/`SCRIPT_NAME`.  When working with fast-cgi's or similar, it's a common need to make all links relative within the app, passing it a `SCRIPT_NAME` via environment variable to let it know to ignore, or "mount at" some prefix.

For example, the acqua frontend/drywall apps might reside in a larger app with other routes to eg, `/`, that conflict with the routes set up here.  In https://github.com/bewest/drywall-rev-proxy/pull/1/files#diff-0364f57fbff2fabbe941ed20c328ef1aR163 I took a shot at using `express.Router( )` to isolate all the existing routes so that we could choose which set of routes to use.  In this case, if the user is logged in, and has permission to view the resource, the resource to serve will actually be proxied.  In any case, I had this need creating a mount prefix both when combining with other projects as side by side modules, and also for proxying, so curious what people think of the idea.  The "prefix" generation in the patch above is a mere quick hack to test whether or not the approach might work (it works, but need something better).

Right now I'm thinking of setting up `config.SCRIPT_NAME`, and prefixing it almost everywhere, looks like there are around 50 places or so.

**Comment by jedireza** [comment] 2015-02-23 01:04
@bewest I think your scenario is an edge case. These apps were not intended to be part of a larger app. The intended use is to create a new app with them as the starting point. I don't want to take this thread off course. Going forward, let's move this discussion into a new issue.

**Comment by ldesplat** [comment] 2015-03-01 03:27
@jedireza That PR has now been released in Lab 5.3.0. Unfortunately, I need to land 1 more PR to make aqua work with it (sourcemaps support issues, need to specify an option to lab's dependency source-map-support). I have a PR for aqua ready as soon as I get that done. I could give it to you but you would get wrong line numbers for coverage and errors right now.

Also, aqua works great with iojs and jsdom 4 (with minor change)!

**Comment by jedireza** [comment] 2015-03-01 18:07
@ldesplat yes, I've been following. Very cool.

**Comment by alex-dixon** [comment] 2015-04-07 22:36
I can't create custom validation error messages for the user signup page (ones that are shown to the user). The messages that show now appear to be coming from Joi. I can't figure out how to disable the Joi messages from showing or to change them to something that I would be able to show a user (at present, the language that shows underneath  form fields on validation error is of the form "keyName" is required). I know this is basic but I've spent about a day trying to figure it out and could use some help.

**Comment by jedireza** [comment] 2015-04-07 22:44
Yeah I was thinking about that during cf9ea49a973b9dc73e23d8b09fee4a8c62298eab. I think you can use `label(...)` to customize the `keyName` but further customizing the validation messages may require that you do validation via a pre-handler.

See: https://github.com/hapijs/joi#anylabelname

If you're willing to share your progress as you learn more I'd be interested in hearing about it.

**Comment by alex-dixon** [comment] 2015-04-07 23:42
Right. ```.label()``` in Joi works as you describe when I tried this: 
```
// signup.js, line 25
 validate: {
                payload: {
                    name: Joi.string().required().label('Your name'),
```
But I need the change the whole message because I'm working on a project that will be in Spanish. I've also tried writing a function under ```pre``` in signup.js and haven't gotten it to work yet. Even if I could:
1. Messages from ```pre``` (like the one you made to check for a duplicate username) appear to be in a class of their own. They show above the signup form, unlike the Joi validation messages, which display underneath the input fields. 
2. The Joi errors would still display under the input fields. I can't figure out how to disable the messages and maintain the validation logic you've provided. 

Me and three fellow n00bs have been stuck on it for about a day. Seems over my head so just thought to ask for help. 

This is a long read but it's definitely pertinent. tl;dr The Joi owners don't think their error messages should ever be shown on the client :
https://github.com/hapijs/joi/issues/546

**Comment by jedireza** [comment] 2015-04-08 00:16
Yes, i18n isn't something I've approached yet.

> 1. Messages from pre (like the one you made to check for a duplicate username) appear to be in a class of their own. They show above the signup form, unlike the Joi validation messages, which display underneath the input fields. 

My suggestion to do your own validation in a `pre` assumes that you'd remove the config validation. Not ideal, I know.

In order for the messages to appear under the form elements, you'd need to emulate the same format that `joi` outputs so the front-end validation parser helper handles them correctly.

Thanks for sharing the link to that discussion, I'll try to read it when I get more time.

**Comment by alex-dixon** [comment] 2015-04-08 05:30
No, thank you! Here's a workaround we found. It needs to be combined with label to be completely custom. Isn't ideal but allows you to set custom error messages that end up being shown to the client. This is server/api/signup underneath inside ```validate``` and after ```payload```, ~ line 50:

```
options: {
                    language: {
                        any: {
                            required: 'Custom try again'
                        },
                        string: {
                            email: 'not the correct format, try again.'

                        }
                    }
                }
            },
```

**Comment by jedireza** [comment] 2015-04-10 06:17
That's actually pretty good, thanks for sharing!

For anyone else following along:
https://github.com/hapijs/joi#validatevalue-schema-options-callback - specifically look for the `language` option.

**Comment by MetaCoderHirschl** [comment] 2015-04-27 20:20
In setup.js, in Asyn.auto, the accounts collection isn't deleted. I noticed I had 'hanging accounts" -- as the user was being deleted at each setup run but not accounts. So I add a delete for accounts:
clean: ['connect', function (done) {

                Async.parallel([
                    User.deleteMany.bind(User, {}),
                    Accounts.deleteMany.bind(Accounts, {}),
                    Admin.deleteMany.bind(Admin, {}),
                    AdminGroup.deleteMany.bind(AdminGroup, {})
                ], done);
            }], 

Cleaned up my database. Thought this might be helpful. Or perhaps I'm missing some other piece of important info.
Thanks for a great repo!

**Comment by jedireza** [comment] 2015-05-01 16:09
@MetaCoderHirschl thanks. I've opened #29 for this.

**Comment by dmt0** [comment] 2015-09-23 06:52
Are there any plans to integrate third-party authentication methods? Perhaps through bell (https://github.com/hapijs/bell)?

**Comment by jedireza** [comment] 2015-09-23 17:38
@dmt0 originally I had planned to include 3rd party strategies. But now I think it's best to keep the code base simpler and leave these types of changes to the consumer of Aqua.

**Comment by andyfenelon** [comment] 2015-10-05 22:35
sorry if this has been asked i skimmed through. 
i'm just curious as to what was the reasoning to use hapi over express ?

**Comment by jedireza** [comment] 2015-10-06 03:54
@andyfenelon I built [Drywall](https://github.com/jedireza/drywall/) with Express and wanted to make something with hapi. :shipit:

**Comment by TomerAvni** [comment] 2015-11-08 07:01
Hi,
I pretty new to node + hapijs (and aqua of course).
I've been trying to simple POST to login (both the api/login and login) but I keep getting either 403 or 400 (Invalid request payload JSON format). I've testing it with Postman with all types body formats (form, x-www and raw) - nothing works for me. I figured it has something to do with validation or more specifically Joi, so I've also tried to enforce the loose formatting by adding:
validate: {
                    options: {
                        stripUnknown: true
                    }
                }
the routes section under connections on the manifest.js.
I would love someone's help with this.
Thanks!

**Comment by jedireza** [comment] 2015-11-08 21:25
FYI: I'm closing this issue since it's really old. Aqua will get updated sometime after react-router hits v1.

@TomerAvni jumping into Aqua without knowing more about the tools it's built with is a lot to take on at one time. There's a [discussion repo](https://github.com/hapijs/discuss/) in the hapi organization where more people could help out with the basics of hapi apps. You may also want to checkout [Frame](https://github.com/jedireza/frame/), which is just the API part of Aqua (and more recently updated).

**Closed by jedireza** 2015-11-08 21:25 UTC
Labels: question
