### ISSUE TITLE
Link to recover password not loading the form to reset the password

### ISSUE THREAD

**Issue by rafahuelin** [jedireza/aqua#196] opened 2017-05-28 15:28 UTC
#Hi there,

After clicking the orange button to reset the password, I received an email to the Gmail account configured on the config.js file.  

After clicking on the link received on the email, the site the page to recover the password loads but it only appears the navbar and the footer. I can see this message on the Terminal:
{"msec":0.4174859970808029,"error":"Not Found","data":{"data":null,"isBoom":true,"isServer":false,"output":{"statusCode":404,"payload":{"statusCode":404,"error":"Not Found"},"headers":{}},"message":"Not Found"}}

I've gone through the installation a few times but I'm finding the same problem all the time. Any idea about what the issue could be?

Thanks,
Rafa

**Comment by jedireza** [comment] 2017-05-28 15:58
Yep looks like it's related to #194 #195 

Closing since this is likely a duplicate of that. If you can test with #194 that would be a big help.

**Closed by jedireza** 2017-05-28 15:58 UTC

**Comment by rafahuelin** [comment] 2017-05-28 17:22
Thanks jedireza, that fix is working in my case :)
